# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: debug-statements
    -   id: check-toml
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-ast
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--filter-files"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
# Black is not strictly required, remove if its causing too much issues
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo:  https://github.com/hadolint/hadolint
    rev: v2.1.0
    hooks:
    -   id: hadolint-docker
-   repo: local
    hooks:
    -   id: docker-build
        name: Build Dockerfile
        language: system
        stages: [push]
        entry: docker
        args: ['build','.','-t','$gaivota_python_nilo_crawler}:latest']
        pass_filenames: false
